# Copyright 2024 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//tools/bazel-docgen/bazel_docgen.gni")

# Create documentation for the Bazel SDK rules
# The following are the public APIs that we are exposing
bazel_docgen("docs") {
  docset_name = "bazel_sdk"
  bazel_targets = [
    "//release/bazel/bazel_sdk/docs:assembly",
    "//release/bazel/bazel_sdk/docs:clang",
    "//release/bazel/bazel_sdk/docs:defs",
    "//release/bazel/bazel_sdk/docs:deps",
    "//release/bazel/bazel_sdk/docs:licenses",
    "//release/bazel/bazel_sdk/docs:products",
    "//release/bazel/bazel_sdk/docs:workflows",
  ]
  reference_repo_path = "sdk/bazel_sdk"
  docsite_base_path = "reference/bazel_sdk"
}
