# Copyright 2023 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Extra vendor-specific targets that may use the deprecated bindings.
import("//vendor/google/build/hlcpp_visibility.gni")

# Targets in this tree.
hlcpp_visibility = [
  # Dependencies between SDK FIDL libraries.
  "//sdk/fidl/*",

  # Unusually located FIDL libraries.
  "//userspace/camera/bin/factory:fuchsia.factory.camera_cpp_hlcpp_conversion",
  "//userspace/camera/bin/factory:fuchsia.factory.camera_hlcpp",
  "//userspace/camera/bin/factory:fuchsia.factory.camera_libfuzzer",

  # FIDL implementation, tests, examples.
  "//examples/fidl/fuchsia.examples:*",
  "//examples/fidl/hlcpp/*",
  "//sdk/ctf/tests/pkg/fidl/cpp:*",
  "//userspace/lib/fostr/*",
  "//userspace/sys/fuzzing/fidl:*",
  "//userspace/testing/fidl/*",
  "//userspace/tests/fidl/*",
  "//tools/fidl/fidlc/testdata:*",
  "//examples/fuzzers/fidl:*",

  # Misc buildsystem stuff.
  "//sdk/ctf/*",

  # Existing in-tree uses of HLCPP that should be removed.
  "//examples/components/config/integration_test:*",
  "//examples/components/config_from_parent/integration_test:*",
  "//examples/components/lifecycle/cpp:*",
  "//examples/components/realm_builder/cpp:*",
  "//examples/components/routing_failed/cpp:*",
  "//examples/components/routing/cpp/echo_client:*",
  "//examples/components/routing/cpp/echo_server:*",
  "//examples/components/routing/fidl:*",
  "//examples/components/routing/integration_tests/cpp:*",
  "//examples/components/services/cpp:*",
  "//examples/components/services/fidl:*",
  "//examples/diagnostics/inspect/codelab/cpp/client:*",
  "//examples/diagnostics/inspect/codelab/cpp/fizzbuzz:*",
  "//examples/diagnostics/inspect/codelab/cpp/part_1:*",
  "//examples/diagnostics/inspect/codelab/cpp/part_2:*",
  "//examples/diagnostics/inspect/codelab/cpp/part_3:*",
  "//examples/diagnostics/inspect/codelab/cpp/part_4:*",
  "//examples/diagnostics/inspect/codelab/cpp/part_5:*",
  "//examples/diagnostics/inspect/codelab/cpp/testing:*",
  "//examples/diagnostics/inspect/codelab/fidl:*",
  "//examples/diagnostics/inspect/cpp:*",
  "//examples/diagnostics/workshop/*",
  "//examples/drivers/driver_test_realm/hermetic/cpp:*",
  "//examples/drivers/transport/tests:*",
  "//examples/fidl/new/canvas/*",
  "//examples/intl/wisdom/*",
  "//sdk/lib/component/tests:*",
  "//sdk/lib/driver/component/cpp:*",
  "//sdk/lib/driver/devfs/cpp:*",
  "//sdk/lib/fuchsia-mem-ext:*",
  "//sdk/lib/images/cpp:*",
  "//sdk/lib/inspect/component/cpp/tests:*",
  "//sdk/lib/inspect/contrib/cpp:*",
  "//sdk/lib/diagnostics/reader/cpp:*",
  "//sdk/lib/media/audio/cpp:*",
  "//sdk/lib/media/cpp:*",
  "//sdk/lib/sys/component/cpp/testing:*",
  "//sdk/lib/sys/component/cpp/tests:*",
  "//sdk/lib/sys/cpp/*",
  "//sdk/lib/sys/service/cpp:*",
  "//sdk/lib/ui/scenic/cpp/*",
  "//sdk/lib/vfs/cpp/*",
  "//sdk/lib/virtualization/testing:*",
  "//userspace/camera/bin/benchmark:*",
  "//userspace/camera/bin/camera-gym/*",
  "//userspace/camera/bin/device/*",
  "//userspace/camera/bin/device_watcher:*",
  "//userspace/camera/bin/factory:lib",
  "//userspace/camera/bin/factory_cli:camera_factory_cli_bin",
  "//userspace/camera/bin/sensor_cli:*",
  "//userspace/camera/bin/usb_device:*",
  "//userspace/camera/bin/virtual_camera:*",
  "//userspace/camera/drivers/controller/*",
  "//userspace/camera/drivers/sensors/imx227:*",
  "//userspace/camera/drivers/test_utils:*",
  "//userspace/camera/drivers/usb_video/uvc-tester:bin",
  "//userspace/camera/drivers/usb_video:*",
  "//userspace/camera/lib/cobalt_logger:*",
  "//userspace/camera/lib/fake_camera:*",
  "//userspace/camera/lib/fake_controller:*",
  "//userspace/camera/lib/fake_legacy_stream:*",
  "//userspace/camera/lib/fake_logical_buffer_collection:*",
  "//userspace/camera/lib/fake_stream:*",
  "//userspace/camera/lib/format_conversion:*",
  "//userspace/camera/lib/formatting:*",
  "//userspace/camera/lib/image_utils:*",
  "//userspace/camera/lib/stream_utils:*",
  "//userspace/camera/lib/virtual_camera:*",
  "//userspace/chromium/web_runner_tests:*",
  "//userspace/cobalt/bin/app:*",
  "//userspace/cobalt/bin/app/fuzzer:*",
  "//userspace/cobalt/bin/system-metrics/*",
  "//userspace/cobalt/bin/testapp:*",
  "//userspace/cobalt/bin/testing:*",
  "//userspace/cobalt/bin/utils:*",
  "//userspace/connectivity/bluetooth/core/bt-host/*",
  "//userspace/connectivity/bluetooth/examples/bt-beacon-reader:*",
  "//userspace/connectivity/bluetooth/examples/bt-le-heart-rate-peripheral:*",
  "//userspace/connectivity/bluetooth/fidl:*",
  "//userspace/connectivity/bluetooth/hci/virtual:*",
  "//userspace/connectivity/bluetooth/tools/bt-hci-tool:*",
  "//userspace/connectivity/ethernet/drivers/asix-88179:*",
  "//userspace/connectivity/network/lib/net_interfaces/cpp:*",
  "//userspace/connectivity/network/mdns/service:*",
  "//userspace/connectivity/network/mdns/util:*",
  "//userspace/connectivity/network/testing/netemul/guest:*",
  "//userspace/connectivity/network/testing/netemul/network-context/fidl:*",
  "//userspace/connectivity/network/testing/netemul/network-context/lib:*",
  "//userspace/connectivity/network/testing/netemul/sync-manager/fidl:*",
  "//userspace/connectivity/network/testing/netemul/sync-manager/lib:*",
  "//userspace/connectivity/network/tests/socket:*",
  "//userspace/connectivity/openthread/third_party/openthread/platform:*",
  "//userspace/connectivity/weave/adaptation:*",
  "//userspace/connectivity/weave/weavestack:*",
  "//userspace/connectivity/wlan/drivers/lib/log/cpp/*",
  "//userspace/connectivity/wlan/drivers/testing/lib/sim-env/*",
  "//userspace/connectivity/wlan/drivers/testing/lib/sim-fake-ap/*",
  "//userspace/connectivity/wlan/drivers/third_party/broadcom/brcmfmac/*",
  "//userspace/connectivity/wlan/drivers/wlanif/*",
  "//userspace/connectivity/wlan/lib/common/cpp:*",
  "//userspace/connectivity/wlan/lib/mlme/cpp/*",
  "//userspace/connectivity/wlan/testing/wlantap-driver:*",
  "//userspace/developer/adb/bin/adb-file-sync:*",
  "//userspace/developer/adb/bin/adb-reboot:*",
  "//userspace/developer/adb/bin/adb:*",
  "//userspace/developer/build_info/*",
  "//userspace/developer/debug/debug_agent/*",
  "//userspace/developer/forensics/crash_reports/*",
  "//userspace/developer/forensics/exceptions/*",
  "//userspace/developer/forensics/feedback_data/*",
  "//userspace/developer/forensics/feedback/*",
  "//userspace/developer/forensics/last_reboot/*",
  "//userspace/developer/forensics/public/fakes:*",
  "//userspace/developer/forensics/snapshot/*",
  "//userspace/developer/forensics/testing/*",
  "//userspace/developer/forensics/utils/*",
  "//userspace/developer/memory/monitor/*",
  "//userspace/developer/process_explorer/*",
  "//userspace/devices/bin/driver_host:*",
  "//userspace/devices/bin/driver_manager:*",
  "//userspace/devices/bus/drivers/platform/test:*",
  "//userspace/devices/lib/sysmem:*",
  "//userspace/devices/securemem/drivers/aml-securemem:*",
  "//userspace/devices/testing/devmgr-integration-test-shim:*",
  "//userspace/devices/testing/driver-integration-test-shim:*",
  "//userspace/devices/tests/banjo-proxy:*",
  "//userspace/devices/tests/bind-test-v2:*",
  "//userspace/devices/tests/bindlib-codegen-test:*",
  "//userspace/devices/tests/device-controller-fidl:*",
  "//userspace/devices/tests/driver-runtime:*",
  "//userspace/devices/tests/driver-transport:*",
  "//userspace/devices/tests/fidl-protocol:*",
  "//userspace/devices/tests/fidl-service:*",
  "//userspace/devices/tests/libdriver-integration-test:*",
  "//userspace/devices/tests/string-bind-test:*",
  "//userspace/diagnostics/archivist/tests/logs/cpp:*",
  "//userspace/diagnostics/validator/inspect/fidl:*",
  "//userspace/diagnostics/validator/inspect/lib/cpp:*",
  "//userspace/diagnostics/validator/logs/fidl:*",
  "//userspace/diagnostics/validator/logs/sink/puppet/cpp:*",
  "//userspace/diagnostics/validator/logs/sink/puppet/sdk:*",
  "//userspace/graphics/bin/agis:*",
  "//userspace/graphics/drivers/msd-arm-mali/tests/unit_tests:*",
  "//userspace/graphics/examples/vkproto/transaction-elimination-test:*",
  "//userspace/graphics/lib/compute/spinel/platforms/vk/tests/spinel_vk_bench/surface:*",
  "//userspace/graphics/tests/libvulkan:*",
  "//userspace/graphics/tests/vkext:*",
  "//userspace/intl/example:*",
  "//userspace/intl/intl_services:*",
  "//userspace/lib/cobalt/cpp:*",
  "//userspace/lib/diagnostics/accessor2logger:*",
  "//userspace/lib/diagnostics/accessor2logger/integration:*",
  "//userspace/lib/fake-clock/fidl:*",
  "//userspace/lib/fake-clock/lib:*",
  "//userspace/lib/fake-clock/named-timer:*",
  "//userspace/lib/fidl_codec/*",
  "//userspace/lib/fidl_fuchsia_intl_ext/cpp:*",
  "//userspace/lib/fsl:*",
  "//userspace/lib/fsl/vmo:*",
  "//userspace/lib/inet",
  "//userspace/lib/intl/intl_property_provider_impl:*",
  "//userspace/lib/intl/lookup/rust:*",
  "//userspace/lib/intl/time_zone_info:*",
  "//userspace/lib/metrics_buffer:*",
  "//userspace/lib/process:*",
  "//userspace/lib/test-suite:*",
  "//userspace/lib/ui/flatland-frame-scheduling:*",
  "//userspace/lib/ui/input-synthesis:*",
  "//userspace/lib/ui/scenic/cpp:*",
  "//userspace/lib/vulkan/flatland_view:*",
  "//userspace/lib/vulkan/swapchain:*",
  "//userspace/media/audio/audio_core:*",
  "//userspace/media/audio/audio_core/mixer:*",
  "//userspace/media/audio/audio_core/test/api:*",
  "//userspace/media/audio/audio_core/test/hardware:*",
  "//userspace/media/audio/audio_core/test/stress:*",
  "//userspace/media/audio/audio_core/testing:*",
  "//userspace/media/audio/audio_core/testing/integration:*",
  "//userspace/media/audio/audio_core/tools/output_pipeline_benchmark:*",
  "//userspace/media/audio/drivers/aml-g12-tdm/*",
  "//userspace/media/audio/drivers/tests:*",
  "//userspace/media/audio/examples/simple_capture:*",
  "//userspace/media/audio/examples/simple_sine:*",
  "//userspace/media/audio/examples/sync_sine:*",
  "//userspace/media/audio/examples/tones:*",
  "//userspace/media/audio/lib/analysis:*",
  "//userspace/media/audio/lib/clock:*",
  "//userspace/media/audio/lib/effects_loader:*",
  "//userspace/media/audio/lib/format:*",
  "//userspace/media/audio/lib/simple-codec:*",
  "//userspace/media/audio/lib/test:*",
  "//userspace/media/audio/lib/wav:*",
  "//userspace/media/audio/services/device_registry/testing:*",
  "//userspace/media/audio/services/mixer/mix:*",
  "//userspace/media/audio/tools/audio_listener:*",
  "//userspace/media/audio/tools/audio-capture-timestamp-validator:*",
  "//userspace/media/audio/tools/audio-effects-ctl:*",
  "//userspace/media/audio/tools/signal_generator:*",
  "//userspace/media/audio/tools/virtual_audio_util:*",
  "//userspace/media/audio/tools/vol:*",
  "//userspace/media/audio/tools/wav_player:*",
  "//userspace/media/audio/tools/wav_recorder:*",
  "//userspace/media/codec/codecs/sw:*",
  "//userspace/media/codec/codecs/sw/aac:*",
  "//userspace/media/codec/codecs/sw/ffmpeg:*",
  "//userspace/media/codec/codecs/sw/sbc:*",
  "//userspace/media/codec/codecs/vaapi:*",
  "//userspace/media/codec/codecs/vaapi/test:*",
  "//userspace/media/codec/examples/encode_camera:*",
  "//userspace/media/codec/examples/encode_file:*",
  "//userspace/media/codec/examples/use_media_decoder:*",
  "//userspace/media/codec/factory:*",
  "//userspace/media/drivers/amlogic_decoder:*",
  "//userspace/media/lib/codec_impl/*",
  "//userspace/media/lib/internal_buffer",
  "//userspace/media/lib/test:*",
  "//userspace/media/playback/examples/audio_player:*",
  "//userspace/media/sounds/soundplayer:*",
  "//userspace/media/testing/mock_profile_provider:*",
  "//userspace/performance/ktrace_provider:*",
  "//userspace/performance/lib/gperftools:*",
  "//userspace/performance/trace_manager:*",
  "//userspace/performance/trace:*",
  "//userspace/power/fidl/testing:*",
  "//userspace/power/testing/thermal-test-control:*",
  "//userspace/power/thermd:*",
  "//userspace/security/bin/tee_manager:*",
  "//userspace/sys/activity:*",
  "//userspace/sys/component_manager/tests/services/src/fidl:*",
  "//userspace/sys/component_manager/tests/structured_config/client_integration/cpp_elf:*",
  "//userspace/sys/component_manager/tests/structured_config/fidl:*",
  "//userspace/sys/fuzzing/common/*",
  "//userspace/sys/fuzzing/libfuzzer:*",
  "//userspace/sys/fuzzing/realmfuzzer/adapters:*",
  "//userspace/sys/fuzzing/realmfuzzer/engine:*",
  "//userspace/sys/fuzzing/realmfuzzer/target:*",
  "//userspace/sys/fuzzing/realmfuzzer/testing:*",
  "//userspace/sys/fuzzing/realmfuzzer/tests:*",
  "//userspace/sys/fuzzing/registry/tests:*",
  "//userspace/sys/test_manager/debug_data_processor:*",
  "//userspace/sys/test_manager/fidl/fuchsia.test.debug:*",
  "//userspace/sys/test_runners/gtest/test_data:*",
  "//userspace/sys/tools/activity-ctl:*",
  "//userspace/sys/tools/log:*",
  "//userspace/testing/loadbench:*",
  "//userspace/testing/system-validation/web/apps:*",
  "//userspace/tests/benchmarks:*",
  "//userspace/tests/microbenchmarks:*",
  "//userspace/ui/a11y/bin/a11y_manager/*",
  "//userspace/ui/a11y/lib/annotation:*",
  "//userspace/ui/a11y/lib/configuration/*",
  "//userspace/ui/a11y/lib/focus_chain/*",
  "//userspace/ui/a11y/lib/gesture_manager/*",
  "//userspace/ui/a11y/lib/input_injection:*",
  "//userspace/ui/a11y/lib/magnifier/*",
  "//userspace/ui/a11y/lib/screen_reader/*",
  "//userspace/ui/a11y/lib/semantics/*",
  "//userspace/ui/a11y/lib/testing:*",
  "//userspace/ui/a11y/lib/tts/*",
  "//userspace/ui/a11y/lib/util/*",
  "//userspace/ui/a11y/lib/view/*",
  "//userspace/ui/a11y/testing:*",
  "//userspace/ui/bin/system_monitor:*",
  "//userspace/ui/bin/virtual_keyboard_manager/*",
  "//userspace/ui/examples/screen_recording:*",
  "//userspace/ui/examples/simplest_sysmem:*",
  "//userspace/ui/input/drivers/ctaphid:*",
  "//userspace/ui/input/lib/hid-input-report:*",
  "//userspace/ui/input/lib/injector/*",
  "//userspace/ui/input/testing/fake_input_report_device:*",
  "//userspace/ui/input/tests/hid:*",
  "//userspace/ui/lib/escher:*",
  "//userspace/ui/scenic/bin:*",
  "//userspace/ui/scenic/lib/allocation:*",
  "//userspace/ui/scenic/lib/display/*",
  "//userspace/ui/scenic/lib/flatland/*",
  "//userspace/ui/scenic/lib/focus:*",
  "//userspace/ui/scenic/lib/image-compression:*",
  "//userspace/ui/scenic/lib/input/*",
  "//userspace/ui/scenic/lib/scenic/*",
  "//userspace/ui/scenic/lib/scheduling:*",
  "//userspace/ui/scenic/lib/screen_capture:*",
  "//userspace/ui/scenic/lib/screen_capture2:*",
  "//userspace/ui/scenic/lib/screenshot/*",
  "//userspace/ui/scenic/lib/shutdown:*",
  "//userspace/ui/scenic/lib/utils:*",
  "//userspace/ui/scenic/lib/view_tree:*",
  "//userspace/ui/scenic/tests:*",
  "//userspace/ui/testing/*",
  "//userspace/ui/tests/conformance_input_tests:*",
  "//userspace/ui/tests/integration_flutter_tests/embedder:*",
  "//userspace/ui/tests/integration_graphics_tests/carnelian-pixel-tests:*",
  "//userspace/ui/tests/integration_graphics_tests/display-pixel-ratio:*",
  "//userspace/ui/tests/integration_graphics_tests/web-pixel-tests:*",
  "//userspace/ui/tests/integration_graphics_tests/web-pixel-tests/chromium_pixel_client:*",
  "//userspace/ui/tests/integration_input_tests/focus:*",
  "//userspace/ui/tests/integration_input_tests/media-buttons:*",
  "//userspace/ui/tests/integration_input_tests/mouse/*",
  "//userspace/ui/tests/integration_input_tests/text-input/*",
  "//userspace/ui/tests/integration_input_tests/touch/*",
  "//userspace/ui/tests/integration_input_tests/touch/touch-flatland-client:*",
  "//userspace/ui/tests/integration_input_tests/virtual-keyboard/*",
  "//userspace/ui/tests/integration_input_tests/web-touch-input/*",
  "//userspace/virtualization/bin/guest_manager:*",
  "//userspace/virtualization/bin/termina_guest_manager:*",
  "//userspace/virtualization/bin/vmm:*",
  "//userspace/virtualization/bin/vmm/device:*",
  "//userspace/virtualization/bin/vmm/device/tests:*",
  "//userspace/virtualization/bin/vmm/device/virtio_magma:*",
  "//userspace/virtualization/bin/vmm/device/virtio_net:*",
  "//userspace/virtualization/lib/grpc:*",
  "//userspace/virtualization/lib/guest_config:*",
  "//userspace/virtualization/lib/guest_interaction:*",
  "//userspace/virtualization/lib/vsh:*",
  "//userspace/virtualization/tests/*",
  "//userspace/zircon/bin/ktrace:*",
  "//userspace/zircon/testing/mutex_pi_exerciser:*",

  # TODO(https://fxbug.dev/376322253): remove abseil from hlcpp allowlist once new C++ binding is supported in cctz and rolled in Fuchsia.
  "//third_party/abseil-cpp/absl/time/internal/cctz:time_zone",
  "//third_party/mesa/src/util/tests/inflight_list:*",
  "//third_party/openweave-core/src/include:*",
  "//third_party/openweave-core/src/inet:*",
  "//tools/create/goldens/my-component-test-cpp:*",
  "//zircon/kernel/lib/devicetree/tests:*",
  "//zircon/system/ulib/ktrace/*",
]

hlcpp_visibility += vendor_hlcpp_visibility
