# Copyright 2024 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//release/rust/rustc_library.gni")

rustc_library("local") {
  name = "fdomain_local"
  edition = "2021"
  with_unit_tests = true

  sources = [ "src/lib.rs" ]

  deps = [
    "//sdk/fidl/fuchsia.io:fuchsia.io_rust",
    "//userspace/lib/fdomain/client",
    "//userspace/lib/fdomain/container",
    "//userspace/lib/fidl/rust/fidl",
    "//userspace/lib/fuchsia-async",
    "//third_party/rust_crates:futures",
  ]
}
