# Copyright 2023 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//release/host.gni")
import("//release/rust/rustc_library.gni")

assert(is_host, "Assembly libraries are host-only")
rustc_library("domain_config") {
  edition = "2021"
  name = "assembly_domain_config"
  version = "0.1.0"
  with_unit_tests = true
  sources = [
    "src/domain_config.rs",
    "src/lib.rs",
  ]
  deps = [
    "//userspace/lib/assembly/constants",
    "//userspace/lib/assembly/platform_configuration",
    "//userspace/lib/fidl/rust/fidl",
    "//userspace/sys/pkg/lib/fuchsia-pkg",
    "//third_party/rust_crates:anyhow",
    "//third_party/rust_crates:camino",
    "//tools/lib/cml",
  ]
  test_deps = [
    "//sdk/fidl/fuchsia.component.decl:fuchsia.component.decl_rust",
    "//userspace/lib/assembly/util",
    "//userspace/lib/assembly/util",
    "//userspace/sys/lib/cm_rust",
    "//userspace/sys/pkg/lib/far/rust:fuchsia-archive",
    "//third_party/rust_crates:assert_matches",
    "//third_party/rust_crates:pretty_assertions",
    "//third_party/rust_crates:tempfile",
  ]
}
