# Copyright 2024 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//release/rust/rustc_library.gni")

rustc_library("errors") {
  edition = "2021"
  deps = [
    "//sdk/fidl/fuchsia.component:fuchsia.component_rust",
    "//sdk/fidl/fuchsia.sys2:fuchsia.sys2_rust",
    "//sdk/rust/zx",
    "//userspace/lib/error/clonable_error",
    "//userspace/lib/fidl/rust/fidl",
    "//userspace/lib/fuchsia-fs",
    "//userspace/sys/component_manager/lib/router_error",
    "//userspace/sys/component_manager/lib/sandbox",
    "//userspace/sys/component_manager/lib/serve_processargs",
    "//userspace/sys/component_manager/lib/serve_processargs",
    "//userspace/sys/lib/cm_config",
    "//userspace/sys/lib/cm_fidl_validator",
    "//userspace/sys/lib/cm_rust",
    "//userspace/sys/lib/cm_types",
    "//userspace/sys/lib/component_id_index",
    "//userspace/sys/lib/config_encoder",
    "//userspace/sys/lib/moniker",
    "//userspace/sys/lib/routing",
    "//third_party/rust_crates:anyhow",
    "//third_party/rust_crates:thiserror",
  ]

  sources = [ "src/lib.rs" ]
}
