# Copyright 2022 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//release/host.gni")
import("//release/rust/rustc_library.gni")

assert(is_host, "Assembly libraries are host-only")

rustc_library("driver_manifest") {
  edition = "2021"
  name = "assembly_driver_manifest"
  version = "0.1.0"
  with_unit_tests = true
  deps = [
    "//userspace/lib/assembly/config_capabilities",
    "//userspace/lib/assembly/config_schema",
    "//userspace/sys/pkg/lib/fuchsia-pkg",
    "//third_party/rust_crates:anyhow",
    "//third_party/rust_crates:camino",
  ]
  test_deps = [
    "//userspace/lib/assembly/file_relative_path",
    "//userspace/lib/assembly/test_util",
    "//third_party/rust_crates:camino",
    "//third_party/rust_crates:serde_json",
    "//third_party/rust_crates:tempfile",
  ]
  sources = [
    "src/driver_manifest.rs",
    "src/lib.rs",
  ]
}
