# Copyright 2021 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//userspace/developer/ffx/build/ffx_plugin.gni")

ffx_plugin("ffx_debug_symbolize") {
  sdk_category = "not-yet-specified"
  version = "0.1.0"
  edition = "2021"

  args_sources = [ "src/args.rs" ]
  args_deps = [
    "//userspace/developer/ffx/core:lib",
    "//third_party/rust_crates:argh",
  ]

  sources = [ "src/lib.rs" ]

  deps = [
    "//userspace/developer/ffx/config:lib",
    "//userspace/developer/ffx/lib/errors:lib",
    "//userspace/developer/ffx/lib/fho:lib",
    "//userspace/developer/ffx/lib/symbol-index",
    "//userspace/developer/ffx/lib/writer:lib",
    "//userspace/lib/fuchsia-async",
    "//third_party/rust_crates:anyhow",
    "//third_party/rust_crates:async-trait",
  ]

  data_deps = [ "//tools/symbolizer" ]
}
