# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//release/fidl/fidl.gni")

fidl("fuchsia.hardware.platform.device") {
  sources = [ "platform-device.fidl" ]
  public_deps = [ "//zircon/vdso/zx" ]
  enable_banjo = true

  # Please do not add to this list!
  # Use //sdk/fidl/fuchsia.hardware.platform.device instead.
  # TODO(https://fxbug.dev/42062127): Remove items from this list.
  visibility = [
    "//sdk/banjo/*",
    "//userspace/devices/bus/drivers/pci:*",
    "//userspace/devices/bus/drivers/platform/*",
    "//userspace/devices/bus/lib/device-protocol-pdev",
    "//userspace/devices/misc/drivers/cpu-trace:*",
    "//vendor/*",
  ]
}
