# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//userspace/developer/ffx/build/ffx_plugin.gni")

ffx_plugin("ffx_doctor") {
  sdk_category = "not-yet-specified"
  version = "0.1.0"
  edition = "2021"
  with_unit_tests = true
  deps = [
    "//sdk/fidl/fuchsia.developer.remotecontrol:fuchsia.developer.remotecontrol_rust",
    "//userspace/connectivity/overnet/lib/core",
    "//userspace/developer/ffx/config:lib",
    "//userspace/developer/ffx/daemon:lib",
    "//userspace/developer/ffx/fidl:fuchsia.developer.ffx_rust",
    "//userspace/developer/ffx/lib/compat_info:lib",
    "//userspace/developer/ffx/lib/doctor_utils:lib",
    "//userspace/developer/ffx/lib/errors:lib",
    "//userspace/developer/ffx/lib/fho:lib",
    "//userspace/developer/ffx/lib/ssh:lib",
    "//userspace/developer/ffx/lib/target:lib",
    "//userspace/developer/ffx/lib/timeout:lib",
    "//userspace/developer/ffx/lib/version:lib",
    "//userspace/developer/ffx/lib/writer:lib",
    "//userspace/developer/ffx/plugins/target/show:ffx_target_show",
    "//userspace/developer/ffx/plugins/target/show:ffx_target_show_args",
    "//userspace/lib/fidl/rust/fidl",
    "//userspace/lib/fuchsia-async",
    "//userspace/lib/fuchsia-lockfile:lib",
    "//third_party/rust_crates:anyhow",
    "//third_party/rust_crates:async-lock",
    "//third_party/rust_crates:async-trait",
    "//third_party/rust_crates:futures",
    "//third_party/rust_crates:serde_json",
    "//third_party/rust_crates:termion",
    "//third_party/rust_crates:tracing",
    "//third_party/rust_crates:zip",
  ]
  test_deps = [
    "//userspace/developer/ffx/plugins/doctor/test_utils:lib",
    "//third_party/rust_crates:tempfile",
  ]

  args_sources = [ "src/args.rs" ]
  args_deps = [
    "//userspace/developer/ffx/core:lib",
    "//third_party/rust_crates:argh",
  ]

  sources = [
    "src/doctor_ledger.rs",
    "src/ledger_view.rs",
    "src/lib.rs",
  ]
}
