# Copyright 2024 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//release/fidl/fidl.gni")

fidl("fuchsia.scheduler.deprecated") {
  sources = [ "profile.fidl" ]
  public_deps = [ "//zircon/vdso/zx" ]
  enable_hlcpp = true
  visibility = [
    # Needed by netstack 2 and its integration tests.
    "//userspace/connectivity/network/netstack:lib",
    "//userspace/connectivity/network/tests/integration/sys:*",

    # Needed by the audio output pipeline benchmarks.
    "//userspace/media/audio/audio_core/tools/output_pipeline_benchmark:*",
    "//vendor/google/media/*",

    # Needed by the RoleManager, which implements this protocol, and its tests.
    "//userspace/zircon/bin/role_manager:*",
    "//userspace/zircon/bin/role_manager/tests/profile:*",
  ]
}
