# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//release/fidl/fidl.gni")

fidl("fuchsia.stash") {
  sources = [ "stash.fidl" ]

  public_deps = [ "//sdk/fidl/fuchsia.mem" ]

  # Stash cannnot not guarantee isolation between clients so its usage must
  # be carefully managed, see https://fxbug.dev/42124367. We intend to deprecate
  # stash and are not accepting new clients.
  #
  # Please don't add entries to this visibility list without approval
  # from the people listed in OWNERS.
  visibility = [
    "//sdk/ctf/tests/fidl/fuchsia.intl/*",
    "//sdk/ctf/tests/fidl/fuchsia.settings/testing/realm-factory/*",
    "//userspace/connectivity/bluetooth/core/bt-gap/*",
    "//userspace/connectivity/bluetooth/testing/*",
    "//userspace/connectivity/bluetooth/tests/bt-manifest-integration-tests/*",
    "//userspace/connectivity/network/dhcpv4/*",
    "//userspace/connectivity/network/netstack",
    "//userspace/connectivity/network/netstack:lib",
    "//userspace/connectivity/network/tests/integration/common:*",
    "//userspace/connectivity/wlan/*",
    "//userspace/settings/service/*",
    "//userspace/settings/storage/*",
    "//userspace/sys/pkg/bin/omaha-client/*",
    "//userspace/sys/stash/*",
    "//userspace/sys/tools/stash_ctl/*",
  ]

  enable_hlcpp = true
}
