# Copyright 2020 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//userspace/developer/ffx/build/ffx_plugin.gni")

ffx_plugin("ffx_component_debug") {
  sdk_category = "not-yet-specified"
  version = "0.1.0"
  edition = "2021"
  deps = [
    "//sdk/fidl/fuchsia.debugger:fuchsia.debugger_rust",
    "//sdk/rust/zx-types",
    "//userspace/developer/debug/ffx_zxdb",
    "//userspace/developer/ffx/lib/errors:lib",
    "//userspace/developer/ffx/lib/fho:lib",
    "//userspace/developer/ffx/lib/target/holders:lib",
    "//userspace/developer/ffx/lib/writer:lib",
    "//userspace/developer/ffx/plugins/component/common:ffx_component",
    "//userspace/sys/lib/component_debug",
    "//third_party/rust_crates:anyhow",
    "//third_party/rust_crates:async-trait",
  ]

  args_sources = [ "src/args.rs" ]
  args_deps = [
    "//userspace/developer/ffx/core:lib",
    "//third_party/rust_crates:argh",
  ]

  sources = [ "src/lib.rs" ]
}
